name: share-tweet

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 10 * * *"

jobs:
  build-and-tweet:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - name: Run Tweet Automator
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Send Tweet
        run: node tweet.js
        env:
          API_KEY: ${{secrets.TWITTER_API_KEY}}
          API_SECRET_KEY: ${{secrets.TWITTER_API_SECRET_KEY}}
          ACCESS_TOKEN: ${{secrets.TWITTER_ACCESS_TOKEN}}
          ACCESS_TOKEN_SECRET: ${{secrets.TWITTER_ACCESS_TOKEN_SECRET}}
