name: share-tweet

on:
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  build-and-tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tweet Automator
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: cd ${GITHUB_WORKSPACE}/tweet-automator/
      - run: ls -la
      - name: Install dependencies
        run: npm install
      - name: Send Tweet
        run: node tweet.js
        env:
          API_KEY: ${{secrets.TWITTER_API_KEY}}
          API_SECRET_KEY: ${{secrets.TWITTER_API_SECRET_KEY}}
          ACCESS_TOKEN: ${{secrets.TWITTER_ACCESS_TOKEN}}
          ACCESS_TOKEN_SECRET: ${{secrets.TWITTER_ACCESS_TOKEN_SECRET}}
