name: share-tweet

on:
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  build-and-tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Run Tweet Automator
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: npm install
        working-directory: ./tweet-automator
      - run: node tweet.js
        working-directory: ./tweet-automator
        env:
          API_KEY: ${{secrets.TWITTER_API_KEY}}
          API_SECRET_KEY: ${{secrets.TWITTER_API_SECRET_KEY}}
          ACCESS_TOKEN: ${{secrets.TWITTER_ACCESS_TOKEN}}
          ACCESS_TOKEN_SECRET: ${{secrets.TWITTER_ACCESS_TOKEN_SECRET}}
